# Generated by Django 3.2.8 on 2022-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField()),
                ('User_Name', models.CharField(max_length=40)),
                ('User_Address', models.CharField(max_length=50)),
            ],
        ),
    ]
